/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PbPerson struct for PbPerson
type PbPerson struct {
	Id     string      `json:"id,omitempty"`
	Image  PbImage     `json:"image,omitempty"`
	Name   string      `json:"name,omitempty"`
	Wallet []PbPayment `json:"wallet,omitempty"`
}
