/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// HandlersAnnouncedUserListItem struct for HandlersAnnouncedUserListItem
type HandlersAnnouncedUserListItem struct {
	AnnouncedEncryptPubkey string `json:"announcedEncryptPubkey,omitempty"`
	AnnouncedSignPubkey    string `json:"announcedSignPubkey,omitempty"`
	AnnouncerSign          string `json:"announcerSign,omitempty"`
	Memo                   string `json:"memo,omitempty"`
	Result                 string `json:"result,omitempty"`
	TimeStamp              int64  `json:"timeStamp,omitempty"`
}
