/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// AppapiGroupContentObjectItem struct for AppapiGroupContentObjectItem
type AppapiGroupContentObjectItem struct {
	Content   string `json:"content,omitempty"`
	Publisher string `json:"publisher,omitempty"`
	TimeStamp int64  `json:"timeStamp,omitempty"`
	TrxId     string `json:"trxId,omitempty"`
	TypeUrl   string `json:"typeUrl,omitempty"`
}
