/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ApiSignTxParam struct for ApiSignTxParam
type ApiSignTxParam struct {
	// ChainID string, the number prefix determines the actual base
	ChainId string `json:"chain_id"`
	// Data hex encode string, include prefix string \"0x\"
	Data     string `json:"data"`
	GasLimit int64  `json:"gas_limit,omitempty"`
	// GasPrice string, the number prefix determines the actual base
	GasPrice string `json:"gas_price,omitempty"`
	Keyalias string `json:"keyalias,omitempty"`
	Keyname  string `json:"keyname,omitempty"`
	Nonce    int64  `json:"nonce,omitempty"`
	// To eth address, e.g.: 0xab...
	To string `json:"to"`
	// Value string, the number prefix determines the actual base
	Value string `json:"value,omitempty"`
}
