/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PbObject struct for PbObject
type PbObject struct {
	Attachments  []interface{}        `json:"attachments,omitempty"`
	AttributedTo []interface{}        `json:"attributedTo,omitempty"`
	Audience     interface{}          `json:"audience,omitempty"`
	Bcc          []interface{}        `json:"bcc,omitempty"`
	Bto          []interface{}        `json:"bto,omitempty"`
	Cc           []interface{}        `json:"cc,omitempty"`
	Content      string               `json:"content,omitempty"`
	Context      interface{}          `json:"context,omitempty"`
	Duration     string               `json:"duration,omitempty"`
	Endtime      TimestamppbTimestamp `json:"endtime,omitempty"`
	File         PbFile               `json:"file,omitempty"`
	Generator    interface{}          `json:"generator,omitempty"`
	Icon         []interface{}        `json:"icon,omitempty"`
	Id           string               `json:"id,omitempty"`
	Image        []PbImage            `json:"image,omitempty"`
	Inreplyto    PbReply              `json:"inreplyto,omitempty"`
	Location     interface{}          `json:"location,omitempty"`
	MediaType    string               `json:"mediaType,omitempty"`
	Name         string               `json:"name,omitempty"`
	Preview      interface{}          `json:"preview,omitempty"`
	Published    TimestamppbTimestamp `json:"published,omitempty"`
	Replies      interface{}          `json:"replies,omitempty"`
	StartTime    TimestamppbTimestamp `json:"startTime,omitempty"`
	Summary      string               `json:"summary,omitempty"`
	Tag          []interface{}        `json:"tag,omitempty"`
	To           []interface{}        `json:"to,omitempty"`
	Type         string               `json:"type,omitempty"`
	Updated      TimestamppbTimestamp `json:"updated,omitempty"`
	Url          []PbLink             `json:"url,omitempty"`
}
