/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// HandlersAnnouncedProducerListItem struct for HandlersAnnouncedProducerListItem
type HandlersAnnouncedProducerListItem struct {
	Action          string `json:"action"`
	AnnouncedPubkey string `json:"announcedPubkey"`
	AnnouncerSign   string `json:"announcerSign"`
	Memo            string `json:"memo"`
	Result          string `json:"result"`
	TimeStamp       int32  `json:"timeStamp"`
}
