/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ApiGroupInfo struct for ApiGroupInfo
type ApiGroupInfo struct {
	AppKey         string          `json:"app_key"`
	CipherKey      string          `json:"cipher_key"`
	ConsensusType  string          `json:"consensus_type"`
	EncryptionType string          `json:"encryption_type"`
	GroupId        string          `json:"group_id"`
	GroupName      string          `json:"group_name"`
	GroupStatus    string          `json:"group_status"`
	HighestBlockId string          `json:"highest_block_id"`
	HighestHeight  int64           `json:"highest_height"`
	LastUpdated    int64           `json:"last_updated"`
	OwnerPubkey    string          `json:"owner_pubkey"`
	SnapshotInfo   ApiSnapshotInfo `json:"snapshot_info,omitempty"`
	UserEthAddr    string          `json:"user_eth_addr"`
	UserPubkey     string          `json:"user_pubkey"`
}
