/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ApiGrpUserParam struct for ApiGrpUserParam
type ApiGrpUserParam struct {
	Action     string `json:"action"`
	GroupId    string `json:"group_id"`
	Memo       string `json:"memo,omitempty"`
	UserPubkey string `json:"user_pubkey"`
}
