/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// HandlersPingResp struct for HandlersPingResp
type HandlersPingResp struct {
	Ttl []int32 `json:"ttl,omitempty"`
}
