/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PbReply struct for PbReply
type PbReply struct {
	Groupid string `json:"groupid,omitempty"`
	Trxid   string `json:"trxid,omitempty"`
}
