/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ApiGroupInfoList struct for ApiGroupInfoList
type ApiGroupInfoList struct {
	Groups []ApiGroupInfo `json:"groups,omitempty"`
}
