/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PbTrx struct for PbTrx
type PbTrx struct {
	Data         []int32 `json:"Data,omitempty"`
	Expired      int32   `json:"Expired,omitempty"`
	GroupId      string  `json:"GroupId,omitempty"`
	Nonce        int32   `json:"Nonce,omitempty"`
	ResendCount  int32   `json:"ResendCount,omitempty"`
	SenderPubkey string  `json:"SenderPubkey,omitempty"`
	SenderSign   []int32 `json:"SenderSign,omitempty"`
	StorageType  int32   `json:"StorageType,omitempty"`
	TimeStamp    string  `json:"TimeStamp,omitempty"`
	TrxId        string  `json:"TrxId,omitempty"`
	Type         int32   `json:"Type,omitempty"`
	Version      string  `json:"Version,omitempty"`
}
