/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// HandlersCreateGroupParam struct for HandlersCreateGroupParam
type HandlersCreateGroupParam struct {
	AppKey         string `json:"app_key"`
	ConsensusType  string `json:"consensus_type"`
	EncryptionType string `json:"encryption_type"`
	GroupName      string `json:"group_name"`
}
