/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PbFile struct for PbFile
type PbFile struct {
	Compression int64   `json:"compression,omitempty"`
	Content     []int64 `json:"content,omitempty"`
	Id          string  `json:"id,omitempty"`
	MediaType   string  `json:"mediaType,omitempty"`
	Name        string  `json:"name,omitempty"`
	Url         string  `json:"url,omitempty"`
}
