/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// HandlersNetworkInfo struct for HandlersNetworkInfo
type HandlersNetworkInfo struct {
	Addrs      []string                          `json:"addrs"`
	EthAddr    string                            `json:"eth_addr"`
	Groups     []HandlersGroupNetworkInfo        `json:"groups"`
	NatEnabled bool                              `json:"nat_enabled"`
	NatType    string                            `json:"nat_type"`
	Node       map[string]map[string]interface{} `json:"node"`
	PeerId     string                            `json:"peer_id"`
}
