/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ApiAddrProtoPair struct for ApiAddrProtoPair
type ApiAddrProtoPair struct {
	Local    string `json:"local,omitempty"`
	Protocol string `json:"protocol,omitempty"`
	Remote   string `json:"remote,omitempty"`
}
