/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PbBlock struct for PbBlock
type PbBlock struct {
	BlockId        string  `json:"BlockId,omitempty"`
	GroupId        string  `json:"GroupId,omitempty"`
	Hash           []int64 `json:"Hash,omitempty"`
	PrevBlockId    string  `json:"PrevBlockId,omitempty"`
	PreviousHash   []int64 `json:"PreviousHash,omitempty"`
	ProducerPubKey string  `json:"ProducerPubKey,omitempty"`
	Signature      []int64 `json:"Signature,omitempty"`
	TimeStamp      string  `json:"TimeStamp,omitempty"`
	Trxs           []PbTrx `json:"Trxs,omitempty"`
}
