/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// ApiSnapshotInfo struct for ApiSnapshotInfo
type ApiSnapshotInfo struct {
	HighestBlockId    string `json:"highestBlockId,omitempty"`
	HighestHeight     int64  `json:"highestHeight,omitempty"`
	Nonce             int64  `json:"nonce,omitempty"`
	SenderPubkey      string `json:"senderPubkey,omitempty"`
	SnapshotPackageId string `json:"snapshotPackageId,omitempty"`
	TimeStamp         int64  `json:"timeStamp,omitempty"`
}
