/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// AppapiCreateJwtParams struct for AppapiCreateJwtParams
type AppapiCreateJwtParams struct {
	AllowGroups []string `json:"allow_groups,omitempty"`
	ExpiresAt   string   `json:"expires_at"`
	Name        string   `json:"name"`
	Role        string   `json:"role"`
}
