/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// AppapiSenderList struct for AppapiSenderList
type AppapiSenderList struct {
	Senders []string `json:"senders,omitempty"`
}
