/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// HandlersGroupSeed struct for HandlersGroupSeed
type HandlersGroupSeed struct {
	AppKey         string  `json:"app_key"`
	CipherKey      string  `json:"cipher_key"`
	ConsensusType  string  `json:"consensus_type"`
	EncryptionType string  `json:"encryption_type"`
	GenesisBlock   PbBlock `json:"genesis_block"`
	GroupId        string  `json:"group_id"`
	GroupName      string  `json:"group_name"`
	OwnerPubkey    string  `json:"owner_pubkey"`
	Signature      string  `json:"signature"`
}
