/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// AppapiRevokeJwtParams struct for AppapiRevokeJwtParams
type AppapiRevokeJwtParams struct {
	GroupId string `json:"group_id,omitempty"`
	Role string `json:"role"`
	Token string `json:"token"`
}
