/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// AppapiCreateJwtParams struct for AppapiCreateJwtParams
type AppapiCreateJwtParams struct {
	ExpiresAt string `json:"expires_at"`
	GroupId string `json:"group_id,omitempty"`
	Name string `json:"name"`
	Role string `json:"role"`
}
