/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk

// HandlersAppConfigKeyItem struct for HandlersAppConfigKeyItem
type HandlersAppConfigKeyItem struct {
	Memo        string `json:"memo,omitempty"`
	Name        string `json:"name,omitempty"`
	OwnerPubkey string `json:"ownerPubkey,omitempty"`
	OwnerSign   string `json:"ownerSign,omitempty"`
	TimeStamp   int64  `json:"timeStamp,omitempty"`
	Type        string `json:"type,omitempty"`
	Value       string `json:"value,omitempty"`
}
