/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// UtilsSuccessResponse struct for UtilsSuccessResponse
type UtilsSuccessResponse struct {
	Success bool `json:"success,omitempty"`
}
