/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// HandlersAppConfigKeyListItem struct for HandlersAppConfigKeyListItem
type HandlersAppConfigKeyListItem struct {
	Name string `json:"name,omitempty"`
	Type string `json:"type,omitempty"`
}
