/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// OptionsJwtListItem struct for OptionsJwtListItem
type OptionsJwtListItem struct {
	Normal []OptionsTokenItem `json:"normal,omitempty"`
	Revoke []OptionsTokenItem `json:"revoke,omitempty"`
}
