/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk

// HandlersNodeInfoMem struct for HandlersNodeInfoMem
type HandlersNodeInfoMem struct {
	// OS memory being used
	HeapAlloc int64 `json:"heap_alloc,omitempty"`
	// OS memory being used
	HeapInuse int64 `json:"heap_inuse,omitempty"`
	// OS memory being used
	HeapSys int64 `json:"heap_sys,omitempty"`
	NumGc   int64 `json:"num_gc,omitempty"`
	// OS memory being used
	StackInuse int64 `json:"stack_inuse,omitempty"`
	// OS memory being used
	StackSys int64 `json:"stack_sys,omitempty"`
	// OS memory being used
	Sys int64 `json:"sys,omitempty"`
}
