/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// HandlersTrxAuthItem struct for HandlersTrxAuthItem
type HandlersTrxAuthItem struct {
	AuthType string `json:"authType,omitempty"`
	TrxType string `json:"trxType,omitempty"`
}
