/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// HandlersGroupNetworkInfo struct for HandlersGroupNetworkInfo
type HandlersGroupNetworkInfo struct {
	GroupId string `json:"GroupId"`
	GroupName string `json:"GroupName"`
	Peers []string `json:"Peers"`
}
