/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// HandlersJoinGroupParamV2 struct for HandlersJoinGroupParamV2
type HandlersJoinGroupParamV2 struct {
	// seed url
	Seed string `json:"seed"`
}
