/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk

// ApiGrpInfoNodeSdk struct for ApiGrpInfoNodeSdk
type ApiGrpInfoNodeSdk struct {
	GroupId      string `json:"group_id,omitempty"`
	LatestUpdate int64  `json:"latest_update,omitempty"`
	Owner        string `json:"owner,omitempty"`
	Provider     string `json:"provider,omitempty"`
	Singature    string `json:"singature,omitempty"`
}
