/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// HandlersNodeInfoMem struct for HandlersNodeInfoMem
type HandlersNodeInfoMem struct {
	// OS memory being used
	HeapAlloc int32 `json:"heap_alloc,omitempty"`
	// OS memory being used
	HeapInuse int32 `json:"heap_inuse,omitempty"`
	// OS memory being used
	HeapSys int32 `json:"heap_sys,omitempty"`
	NumGc int32 `json:"num_gc,omitempty"`
	// OS memory being used
	StackInuse int32 `json:"stack_inuse,omitempty"`
	// OS memory being used
	StackSys int32 `json:"stack_sys,omitempty"`
	// OS memory being used
	Sys int32 `json:"sys,omitempty"`
}
