/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// ApiPubkeyParam struct for ApiPubkeyParam
type ApiPubkeyParam struct {
	EncodedPubkey string `json:"encoded_pubkey"`
}
