/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk

// PbProducerItem struct for PbProducerItem
type PbProducerItem struct {
	Action           int64  `json:"Action,omitempty"`
	GroupId          string `json:"GroupId,omitempty"`
	GroupOwnerPubkey string `json:"GroupOwnerPubkey,omitempty"`
	GroupOwnerSign   string `json:"GroupOwnerSign,omitempty"`
	Memo             string `json:"Memo,omitempty"`
	ProducerPubkey   string `json:"ProducerPubkey,omitempty"`
	TimeStamp        string `json:"TimeStamp,omitempty"`
	WithnessBlocks   int64  `json:"WithnessBlocks,omitempty"`
}
