/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// OptionsJwt struct for OptionsJwt
type OptionsJwt struct {
	Chain OptionsJwtListItem `json:"chain,omitempty"`
	Key string `json:"key,omitempty"`
	Node map[string]OptionsJwtListItem `json:"node,omitempty"`
}
