/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// HandlersPostToGroupParam struct for HandlersPostToGroupParam
type HandlersPostToGroupParam struct {
	// Data Example:  {   \"type\": \"Create\",   \"object\": {    \"type\": \"Note\",    \"id\": 1,    \"content\": \"hello world\"   }  }
	Data map[string]map[string]interface{} `json:"data"`
	GroupId string `json:"group_id"`
}
