/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// HandlersClearGroupDataParam struct for HandlersClearGroupDataParam
type HandlersClearGroupDataParam struct {
	GroupId string `json:"group_id"`
}
