/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// PbBlock struct for PbBlock
type PbBlock struct {
	BlockHash []int32 `json:"BlockHash,omitempty"`
	BlockId int32 `json:"BlockId,omitempty"`
	Epoch int32 `json:"Epoch,omitempty"`
	GroupId string `json:"GroupId,omitempty"`
	PrevHash []int32 `json:"PrevHash,omitempty"`
	ProducerPubkey string `json:"ProducerPubkey,omitempty"`
	ProducerSign []int32 `json:"ProducerSign,omitempty"`
	Sudo bool `json:"Sudo,omitempty"`
	TimeStamp string `json:"TimeStamp,omitempty"`
	Trxs []PbTrx `json:"Trxs,omitempty"`
}
