/*
 * rum
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rum_sdk
// ApiNSdkSendTrxParams struct for ApiNSdkSendTrxParams
type ApiNSdkSendTrxParams struct {
	Data string `json:"data"`
	SenderPubkey string `json:"sender_pubkey"`
	SenderSign string `json:"sender_sign"`
	// nanosecond
	Timestamp string `json:"timestamp,omitempty"`
	TrxId string `json:"trx_id"`
	Version string `json:"version"`
}
